# Name of your workflow
name: CI/CD Pipeline for Node.js App

# Trigger the workflow on a push to the main branch
on:
  push:
    branches: [ "main" ]

# Define the jobs that will run
jobs:
  test:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    # Define the steps for this job
    steps:
      # 1. Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test

  build-and-push:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest
    # This job depends on the 'test' job
    needs: test

    # Define the steps for this job
    steps:
      # 1. Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to DockerHub using the secrets
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build the Docker image and push it to DockerHub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shizanourin/nodejs-demo-app:latest